# Generated by Django 4.2.1 on 2023-12-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("add", models.CharField(max_length=60)),
                ("dob", models.DateField()),
                ("mob", models.IntegerField()),
            ],
        ),
    ]
