# Generated by Django 4.2.8 on 2023-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_bs", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="limit",
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
            preserve_default=False,
        ),
    ]
