# Generated by Django 4.2.8 on 2023-12-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_bs", "0003_transaction_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="withdrawal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
